services:
  redis:
    image: redis:alpine3.16
  db:
    image: postgres:14.4-alpine
    env_file:
      - .env.local
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
  django:
    build: .
    command: python src/manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - .env.local
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./message_images:/app/message_images
  worker:
    build: .
    command: python src/manage.py rqworker
    env_file:
      - .env.local
    volumes:
      - ./message_images:/app/message_images
  migration:
    build: .
    command: python src/manage.py migrate
    env_file:
      - .env.local
    depends_on:
      db:
        condition: service_healthy
  create-superuser:
    build: .
    command: python src/manage.py createsuperuser --noinput
    env_file:
      - .env.local
    depends_on:
      migration:
        condition: service_completed_successfully

volumes:
  postgres_data:
  message_images: